num=int(input("write a number"))
print("Number 1:",num)
num2=int(input("write 2nd number"))
print("Number 2",num2)
print("The sum of the numbers:",num+num2)
print("The product of the numbers:",num*num2)